# Generated by Django 4.0.4 on 2022-04-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='MyForm',
        ),
    ]
