# Generated by Django 4.0.4 on 2022-05-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0002_rename_form_myform'),
    ]

    operations = [
        migrations.AddField(
            model_name='myform',
            name='score',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
